#ifndef LEX_TYPES_H
#define LEX_TYPES_H

    #define INCLUDE_TOKEN       100
    #define DEFINE_TOKEN        101
    #define TYPE_TOKEN          102
    #define FOR_TOKEN           103
    #define WHILE_TOKEN         104
    #define DO_TOKEN            105
    #define IF_TOKEN            106
    #define ELSE_TOKEN          107
    #define BREAK_TOKEN         108
    #define CONTINUE_TOKEN      109
    #define RETURN_TOKEN        110
    #define IDENT_TOKEN         111
    #define INTCONST_TOKEN      112
    #define STRCONST_TOKEN      113
    #define CHARCONST_TOKEN     114
    #define INCLUDE_FILE_TOKEN  115
    #define LPAR_TOKEN          116
    #define RPAR_TOKEN          117
    #define LBRACKET_TOKEN      118
    #define RBRACKET_TOKEN      119
    #define LBRACE_TOKEN        120
    #define RBRACE_TOKEN        121
    #define COMMA_TOKEN         122
    #define SEMI_TOKEN          123
    #define QUEST_TOKEN         124
    #define COLON_TOKEN         125
    #define EQUAL_TOKEN         126
    #define NEQUAL_TOKEN        127
    #define GT_TOKEN            128
    #define GE_TOKEN            129
    #define LT_TOKEN            130
    #define LE_TOKEN            131
    #define PLUS_TOKEN          132
    #define MINUS_TOKEN         133
    #define STAR_TOKEN          134
    #define SLASH_TOKEN         135
    #define MOD_TOKEN           136
    #define TILDE_TOKEN         137
    #define PIPE_TOKEN          138
    #define BANG_TOKEN          139
    #define AMP_TOKEN           140
    #define DAMP_TOKEN          141
    #define DPIPE_TOKEN         142
    #define ASSIGN_TOKEN        143
    #define PLUSASSIGN_TOKEN    144
    #define MINUSASSIGN_TOKEN   145
    #define STARASSIGN_TOKEN    146
    #define SLASHASSIGN_TOKEN   147
    #define INCR_TOKEN          148
    #define DECR_TOKEN          149
    #define UNKNOWN_TOKEN       150
    #define REALCONST_TOKEN     151   
#endif
