#ifndef LEX_TYPES_H
#define LEX_TYPES_H

    #define INCLUDE_TOKEN       0x01
    #define DEFINE_TOKEN        0x02
    #define TYPE_TOKEN          0x03
    #define FOR_TOKEN           0x04
    #define WHILE_TOKEN         0x05
    #define DO_TOKEN            0x06
    #define IF_TOKEN            0x07
    #define ELSE_TOKEN          0x08
    #define BREAK_TOKEN         0x09
    #define CONTINUE_TOKEN      0x0A
    #define RETURN_TOKEN        0x0B
    #define IDENT_TOKEN         0x0C
    #define INTCONST_TOKEN      0x0D
    #define STRCONST_TOKEN      0x0E
    #define CHARCONST_TOKEN     0x0F
    #define INCLUDE_FILE_TOKEN  0x10
    #define LPAR_TOKEN          0x11
    #define RPAR_TOKEN          0x12
    #define LBRACKET_TOKEN      0x13
    #define RBRACKET_TOKEN      0x14
    #define LBRACE_TOKEN        0x15
    #define RBRACE_TOKEN        0x16
    #define COMMA_TOKEN         0x17
    #define SEMI_TOKEN          0x18
    #define QUEST_TOKEN         0x19
    #define COLON_TOKEN         0x1A
    #define EQUAL_TOKEN         0x1B
    #define NEQUAL_TOKEN        0x1C
    #define GT_TOKEN            0x1D
    #define GE_TOKEN            0x1E
    #define LT_TOKEN            0x1F
    #define LE_TOKEN            0x20
    #define PLUS_TOKEN          0x21
    #define MINUS_TOKEN         0x22
    #define STAR_TOKEN          0x23
    #define SLASH_TOKEN         0x24
    #define MOD_TOKEN           0x25
    #define TILDE_TOKEN         0x26
    #define PIPE_TOKEN          0x27
    #define BANG_TOKEN          0x28
    #define AMP_TOKEN           0x29
    #define DAMP_TOKEN          0x2A
    #define DPIPE_TOKEN         0x2B
    #define ASSIGN_TOKEN        0x2C
    #define PLUSASSIGN_TOKEN    0x2D
    #define MINUSASSIGN_TOKEN   0x2E
    #define STARASSIGN_TOKEN    0x2F
    #define SLASHASSIGN_TOKEN   0x30
    #define INCR_TOKEN          0x31
    #define DECR_TOKEN          0x32
    #define UNKNOWN_TOKEN       0x33
    #define REALCONST_TOKEN     0x34  
    #define IFNDEF_TOKEN        0x35
    #define IFDEF_TOKEN         0x36
    #define ENDIF_TOKEN         0x37
    #define ELIF_TOKEN          0x38
    #define ElSE_DIREC_TOKEN    0x39
    #define HEXCONST_TOKEN      0x3A
    #define UNDEF_TOKEN         0x3B
    #define NEWLINE_TOKEN       0x3C

#endif
